<%@ Page Language="VB" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to 1st-repos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
            color: #333;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
            color: #0366d6;
            border-bottom: 2px solid #0366d6;
            padding-bottom: 10px;
        }
        p {
            line-height: 1.6;
        }
        .info {
            background-color: #f0f8ff;
            padding: 15px;
            border-left: 4px solid #0366d6;
            margin: 20px 0;
        }
        .timestamp {
            color: #666;
            font-size: 0.9em;
            margin-top: 20px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to 1st-repos</h1>
        <p>This is the default ASP page for your repository.</p>
        
        <div class="info">
            <strong>Server Information:</strong>
            <p>
                <% 
                    Response.Write("Server Name: " & Request.ServerVariables("SERVER_NAME") & "<br>")
                    Response.Write("Server Port: " & Request.ServerVariables("SERVER_PORT") & "<br>")
                    Response.Write("Request Method: " & Request.ServerVariables("REQUEST_METHOD") & "<br>")
                %>
            </p>
        </div>

        <div class="info">
            <strong>Current Date & Time:</strong>
            <p>
                <% Response.Write(Now()) %>
            </p>
        </div>

        <p>You can customize this page by editing <code>default.asp</code> in your repository.</p>

        <div class="timestamp">
            <em>Generated by ASP Server</em>
        </div>
    </div>
</body>
</html>
